//! `fiducia completion <shell>` — print a static shell completion script.
//!
//! The script is generated by the flags-2-env core from `.cli-flags.toml`, so
//! it stays correct as flags change, and it does no TOML reading or process
//! spawning while the shell is completing.
//!
//! ```sh
//! fiducia completion --shell bash > ~/.local/share/bash-completion/completions/fiducia
//! fiducia completion --shell zsh  > ~/.zfunc/_fiducia
//! ```

use std::path::Path;

use crate::error::CliError;
use crate::flags::CliArgs;

pub fn run(args: &CliArgs, config_path: &Path) -> Result<i32, CliError> {
    let script = crate::help::completion_script(config_path, &args.shell, crate::PROGRAM)?;
    // Deliberately not `emit`: the output is a shell script, so `--json` does
    // not apply and must not wrap it.
    print!("{script}");
    Ok(0)
}
