// Generated by flags2env from .cli-flags.toml. Do not edit.

#[allow(non_snake_case)]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CliConfig {
    pub FIDUCIA_REGIONS_FILE: String,
    pub FIDUCIA_SAMPLES: i64,
    pub FIDUCIA_HEALTH_PATH: String,
    pub FIDUCIA_TIMEOUT_MS: i64,
    pub FIDUCIA_WARMUP: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FIDUCIA_ONLY_REGION: Option<String>,
    pub FIDUCIA_JSON: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FLAGS2ENV_COMMAND: Option<String>,
}
